environment:
    install_berry_perl: "cmd /C git clone https://github.com/stevieb9/berrybrew && cd berrybrew/bin && berrybrew.exe install %version% && berrybrew.exe switch %version%"
    install_active_perl: "cmd /C choco install activeperl -version %version%"

    matrix:
      - install_perl: "%install_berry_perl%"
        version: "5.26.3_64"
        ALIEN_INSTALL_TYPE: share
      - install_perl: "%install_berry_perl%"
        version: "5.26.3_64"
        ALIEN_INSTALL_TYPE: system

install:
  # Install perl
  - cmd: "%install_perl%"
  # Make sure we are in project root
  - cmd: "cd %APPVEYOR_BUILD_FOLDER%"
  # Set path for berrybrew
  - SET PATH=C:\Perl5\bin;C:\berrybrew\%version%\c\bin;C:\berrybrew\%version%\perl\site\bin;C:\berrybrew\%version%\perl\bin;%PATH%
  - SET PERL5LIB=C:/Perl5/lib/perl5
  - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
  - SET PERL_MB_OPT=--install_base C:/Perl5
  - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
  - cpanm -n Alien::Build::Plugin::Decode::SourceForge
  - cpanm -n Dist::Zilla::PluginBundle::Author::Plicease
  - dzil authordeps --missing | cpanm
  - dzil listdeps --missing | cpanm


build: off

test_script:
  - dzil test -v

shallow_clone: true

cache:
  - C:\Perl5
