language: perl
sudo: false

install:
  - perlbrew list
  - ./maint/travis-install-mods
  - af missing --plugin | cpanm -n
  - af missing          | cpanm -n
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n || true

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v
